function [MeanImg,PCs,Vars] = pca_train

% Get a matrix in which each column is a training image
[Imgs,nr,nc] = load_train_images();
M = size( Imgs, 1 );    % Number of images
N = size( Imgs, 2 );    % Number of pixels in each image

% Normalize the images to mean 0 and stddev 1
Imgs = normalize_images( Imgs );

% Get the mean image and subtract from all original images
MeanImg = mean( Imgs, 2 );
Imgs = Imgs - repmat( MeanImg, 1, N );

% Use SVD to get the eigenvectors of the covariance 1/(N-1) * Imgs*Imgs'
[PCs,S,V] = svd( Imgs / sqrt(N-1) );
Vars = diag(S);
MeanImg = reshape(MeanImg',nc,nr)';

%-------------------------------------------------------
%                     Functions
%-------------------------------------------------------

% Normalize each image to mean 0, standard deviation 1
function Imgs = normalize_images( Imgs )
  M = size( Imgs, 1 );
  N = size( Imgs, 2 );
  Means = mean( Imgs );
  Imgs = Imgs - repmat( Means, M, 1 );
  Stddevs = sqrt( mean( Imgs.^2 ) * M / (M-1));
  Imgs = Imgs ./ repmat( Stddevs, M, 1 );

function [X,nr,nc] = load_train_images
  Names = train_files();
  N = size(Names,1);
  for i=1:N
    Img = imread( deblank( Names(i,:) ));
    if i==1
      M = prod(size(Img));
      nr = size(Img,1);
      nc = size(Img,2);
      X = zeros( M, N );
    elseif prod(size(Img)) ~= M
      error( 'image sizes must agree' );
    end;
    X(:,i) = reshape(Img',M,1);
  end;

function Files = train_files

  Files = [ 'Examples/name_10.png';
            'Examples/name_100.png';
            'Examples/name_1000.png';
            'Examples/name_1001.png';
            'Examples/name_1002.png';
            'Examples/name_1003.png';
            'Examples/name_1004.png';
            'Examples/name_1005.png';
            'Examples/name_1006.png';
            'Examples/name_1007.png';
            'Examples/name_1008.png';
            'Examples/name_1009.png';
            'Examples/name_101.png';
            'Examples/name_1010.png';
            'Examples/name_1011.png';
            'Examples/name_1012.png';
            'Examples/name_1013.png';
            'Examples/name_1014.png';
            'Examples/name_1015.png';
            'Examples/name_1016.png';
            'Examples/name_1018.png';
            'Examples/name_1019.png';
            'Examples/name_102.png';
            'Examples/name_1021.png';
            'Examples/name_1022.png';
            'Examples/name_1023.png';
            'Examples/name_1024.png';
            'Examples/name_1025.png';
            'Examples/name_1026.png';
            'Examples/name_1028.png';
            'Examples/name_1029.png';
            'Examples/name_103.png';
            'Examples/name_1030.png';
            'Examples/name_1031.png';
            'Examples/name_1032.png';
            'Examples/name_1033.png';
            'Examples/name_1035.png';
            'Examples/name_1036.png';
            'Examples/name_1038.png';
            'Examples/name_1039.png';
            'Examples/name_104.png';
            'Examples/name_1040.png';
            'Examples/name_1041.png';
            'Examples/name_1042.png';
            'Examples/name_1043.png';
            'Examples/name_1044.png';
            'Examples/name_1045.png';
            'Examples/name_1046.png';
            'Examples/name_1047.png';
            'Examples/name_1048.png';
            'Examples/name_1049.png';
            'Examples/name_105.png';
            'Examples/name_1050.png';
            'Examples/name_1051.png';
            'Examples/name_1052.png';
            'Examples/name_1053.png';
            'Examples/name_1054.png';
            'Examples/name_1055.png';
            'Examples/name_1056.png';
            'Examples/name_1057.png';
            'Examples/name_1058.png';
            'Examples/name_1059.png';
            'Examples/name_106.png';
            'Examples/name_1060.png';
            'Examples/name_1061.png';
            'Examples/name_1062.png';
            'Examples/name_1063.png';
            'Examples/name_1066.png';
            'Examples/name_1067.png';
            'Examples/name_1068.png';
            'Examples/name_1069.png';
            'Examples/name_107.png';
            'Examples/name_1070.png';
            'Examples/name_1071.png';
            'Examples/name_1072.png';
            'Examples/name_1073.png';
            'Examples/name_1074.png';
            'Examples/name_1075.png';
            'Examples/name_1076.png';
            'Examples/name_1077.png';
            'Examples/name_1078.png';
            'Examples/name_1079.png';
            'Examples/name_108.png';
            'Examples/name_1080.png';
            'Examples/name_1081.png';
            'Examples/name_1082.png';
            'Examples/name_1083.png';
            'Examples/name_1084.png';
            'Examples/name_1085.png';
            'Examples/name_1086.png';
            'Examples/name_1087.png';
            'Examples/name_1088.png';
            'Examples/name_109.png';
            'Examples/name_1091.png';
            'Examples/name_1092.png';
            'Examples/name_1093.png';
            'Examples/name_1094.png';
            'Examples/name_1095.png';
            'Examples/name_1096.png';
            'Examples/name_1097.png';
            'Examples/name_1098.png';
            'Examples/name_1099.png';
            'Examples/name_11.png';
            'Examples/name_110.png';
            'Examples/name_1105.png';
            'Examples/name_1106.png';
            'Examples/name_1107.png';
            'Examples/name_1108.png';
            'Examples/name_1109.png';
            'Examples/name_111.png';
            'Examples/name_1111.png';
            'Examples/name_1112.png';
            'Examples/name_1113.png';
            'Examples/name_1117.png';
            'Examples/name_1118.png';
            'Examples/name_1119.png';
            'Examples/name_112.png';
            'Examples/name_1120.png';
            'Examples/name_1121.png';
            'Examples/name_1122.png';
            'Examples/name_1123.png';
            'Examples/name_1124.png';
            'Examples/name_1125.png';
            'Examples/name_1126.png';
            'Examples/name_1127.png';
            'Examples/name_1128.png';
            'Examples/name_1129.png';
            'Examples/name_113.png';
            'Examples/name_1130.png';
            'Examples/name_1131.png';
            'Examples/name_1132.png';
            'Examples/name_1133.png';
            'Examples/name_1134.png';
            'Examples/name_1135.png';
            'Examples/name_1136.png';
            'Examples/name_1137.png';
            'Examples/name_1138.png';
            'Examples/name_1139.png';
            'Examples/name_114.png';
            'Examples/name_1140.png';
            'Examples/name_1141.png';
            'Examples/name_1142.png';
            'Examples/name_1143.png';
            'Examples/name_1144.png';
            'Examples/name_1145.png';
            'Examples/name_1146.png';
            'Examples/name_1147.png';
            'Examples/name_1148.png';
            'Examples/name_1149.png';
            'Examples/name_115.png';
            'Examples/name_1150.png';
            'Examples/name_1151.png';
            'Examples/name_1152.png';
            'Examples/name_1153.png';
            'Examples/name_1154.png';
            'Examples/name_1155.png';
            'Examples/name_1156.png';
            'Examples/name_1157.png';
            'Examples/name_1158.png';
            'Examples/name_1159.png';
            'Examples/name_116.png';
            'Examples/name_1161.png';
            'Examples/name_1162.png';
            'Examples/name_1163.png';
            'Examples/name_1164.png';
            'Examples/name_1166.png';
            'Examples/name_1167.png';
            'Examples/name_1168.png';
            'Examples/name_1169.png';
            'Examples/name_117.png';
            'Examples/name_1170.png';
            'Examples/name_1171.png';
            'Examples/name_1172.png';
            'Examples/name_1173.png';
            'Examples/name_1174.png';
            'Examples/name_1175.png';
            'Examples/name_1177.png';
            'Examples/name_1178.png';
            'Examples/name_1179.png';
            'Examples/name_118.png';
            'Examples/name_1183.png';
            'Examples/name_1184.png';
            'Examples/name_1185.png';
            'Examples/name_1186.png';
            'Examples/name_1187.png';
            'Examples/name_1188.png';
            'Examples/name_1189.png';
            'Examples/name_119.png';
            'Examples/name_1190.png';
            'Examples/name_1191.png';
            'Examples/name_1192.png';
            'Examples/name_1193.png';
            'Examples/name_1194.png';
            'Examples/name_1195.png';
            'Examples/name_1196.png';
            'Examples/name_1197.png';
            'Examples/name_1198.png';
            'Examples/name_1199.png';
            'Examples/name_12.png';
            'Examples/name_120.png';
            'Examples/name_1200.png';
            'Examples/name_1201.png';
            'Examples/name_1202.png';
            'Examples/name_1203.png';
            'Examples/name_1204.png';
            'Examples/name_1205.png';
            'Examples/name_1206.png';
            'Examples/name_1207.png';
            'Examples/name_1208.png';
            'Examples/name_1209.png';
            'Examples/name_121.png';
            'Examples/name_1211.png';
            'Examples/name_1212.png';
            'Examples/name_1215.png';
            'Examples/name_1216.png';
            'Examples/name_1217.png';
            'Examples/name_1218.png';
            'Examples/name_1219.png';
            'Examples/name_122.png';
            'Examples/name_1220.png';
            'Examples/name_1221.png';
            'Examples/name_1222.png';
            'Examples/name_1223.png';
            'Examples/name_1224.png';
            'Examples/name_1225.png';
            'Examples/name_1226.png';
            'Examples/name_1227.png';
            'Examples/name_1228.png';
            'Examples/name_1229.png';
            'Examples/name_123.png';
            'Examples/name_1230.png';
            'Examples/name_1231.png';
            'Examples/name_1232.png';
            'Examples/name_1233.png';
            'Examples/name_1234.png';
            'Examples/name_1235.png';
            'Examples/name_1236.png';
            'Examples/name_1237.png';
            'Examples/name_1238.png';
            'Examples/name_1239.png';
            'Examples/name_124.png';
            'Examples/name_1240.png';
            'Examples/name_1241.png';
            'Examples/name_1242.png';
            'Examples/name_1243.png';
            'Examples/name_1244.png';
            'Examples/name_1246.png';
            'Examples/name_1247.png';
            'Examples/name_1248.png';
            'Examples/name_1249.png';
            'Examples/name_125.png';
            'Examples/name_1250.png';
            'Examples/name_1251.png';
            'Examples/name_1252.png';
            'Examples/name_1253.png';
            'Examples/name_1254.png';
            'Examples/name_1256.png';
            'Examples/name_1257.png';
            'Examples/name_1258.png';
            'Examples/name_1259.png';
            'Examples/name_126.png';
            'Examples/name_1260.png';
            'Examples/name_1261.png';
            'Examples/name_1262.png';
            'Examples/name_1263.png';
            'Examples/name_1264.png';
            'Examples/name_1265.png';
            'Examples/name_1266.png';
            'Examples/name_1267.png';
            'Examples/name_127.png';
            'Examples/name_1270.png';
            'Examples/name_1271.png';
            'Examples/name_1272.png';
            'Examples/name_1273.png';
            'Examples/name_1274.png';
            'Examples/name_1275.png';
            'Examples/name_1276.png';
            'Examples/name_1277.png';
            'Examples/name_1278.png';
            'Examples/name_1279.png';
            'Examples/name_128.png';
            'Examples/name_1280.png';
            'Examples/name_1281.png';
            'Examples/name_1282.png';
            'Examples/name_1283.png';
            'Examples/name_1284.png';
            'Examples/name_1285.png';
            'Examples/name_1286.png';
            'Examples/name_1287.png';
            'Examples/name_1288.png';
            'Examples/name_1289.png';
            'Examples/name_129.png';
            'Examples/name_1290.png';
            'Examples/name_1292.png';
            'Examples/name_1294.png';
            'Examples/name_1295.png';
            'Examples/name_1296.png';
            'Examples/name_1297.png';
            'Examples/name_1298.png';
            'Examples/name_1299.png'
  ];

